

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: contact-us-warmup_development

test:
  <<: *default
  database: contact-us-warmup_test


production:
  <<: *default
  database: contact-us-warmup_production
